/**
 * Generates `generated/tools.ts` — the committed MCP tool manifest.
 *
 * Fetches the four Alpaca OpenAPI specs (the same sources that produce the
 * `types/*.ts` definitions) and writes the distilled {@link ToolManifest} as a
 * plain TypeScript module. Run via `bun run generate` (chained after
 * `openapi-typescript`) or directly: `bun run src/generate-tools.ts`.
 *
 * Note: `authx.yaml` is served as JSON despite its extension.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SPEC_SOURCES, buildTools } from './build-tools';

async function fetchDocs(): Promise<Record<string, any>> {
  const entries = await Promise.all(
    Object.entries(SPEC_SOURCES).map(async ([api, { url }]) => {
      const res = await fetch(url, { redirect: 'follow' });
      if (!res.ok) throw new Error(`Failed to fetch ${api} spec (${url}): ${res.status} ${res.statusText}`);
      return [api, JSON.parse(await res.text())] as const;
    })
  );
  return Object.fromEntries(entries);
}

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, 'generated', 'tools.ts');

const manifest = buildTools(await fetchDocs());

// One tool per line keeps the (large) generated file diff-friendly and within
// editor line limits, while staying compact.
const toolLines = manifest.tools.map((tool) => `  ${JSON.stringify(tool)},`).join('\n');
const source = `/**
 * AUTO-GENERATED by \`src/generate-tools.ts\` — do not edit by hand.
 * Run \`bun run generate\` to rebuild from the live Alpaca OpenAPI specs.
 */
import type { ToolManifest } from '../manifest-types';

export const manifest: ToolManifest = {
  apis: ${JSON.stringify(manifest.apis)},
  tools: [
${toolLines}
  ],
};
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, source);
process.stderr.write(`Wrote ${manifest.tools.length} tools across ${Object.keys(manifest.apis).length} APIs to ${outFile}\n`);
