/**
 * @alpaca-open-api/core
 *
 * Typed fetch clients, model types, and per-API routing for the Alpaca APIs
 * (Trading, Market Data, Broker, AuthX) - all generated by Orval from the
 * official specs (run `bun run generate`). Every client routes HTTP through the
 * shared {@link makeMutator | mutator}, which resolves host (paper/live +
 * `ALPACA_*_URL` overrides; live by default) and auth per API.
 *
 * @see https://docs.alpaca.markets/
 */

// Per-API host + auth routing, and the shared mutator behind every generated client.
export { API_ROUTING } from './api-routing';
export type { ApiMeta, AuthStrategy } from './api-routing';
export { makeMutator, tradingMutator, dataMutator, brokerMutator, authxMutator } from './mutator';

// Per-request credential context for remote (HTTP) deployments - the mutator reads
// it when set, else falls back to the process environment (stdio mode).
export { reqCtx } from './request-context';
export type { Creds, CredsStore, AlpacaEnv } from './request-context';

// Typed fetch clients, one namespace per API - e.g. `tradingApi.getAccount()`,
// `dataApi.stockLatestQuoteSingle(...)`. Credentials/host come from the env the
// mutator reads (ALPACA_API_KEY/SECRET, ALPACA_ENV).
export * as tradingApi from './generated/trading/client';
export * as dataApi from './generated/data/client';
export * as brokerApi from './generated/broker/client';
export * as authxApi from './generated/authx/client';

// Model (schema) types, one namespace per API - e.g. `tradingModel.Account`.
export * as tradingModel from './generated/trading/model';
export * as dataModel from './generated/data/model';
export * as brokerModel from './generated/broker/model';
export * as authxModel from './generated/authx/model';
