/**
 * @alpaca-open-api/core
 *
 * Typed fetch clients, model types, and per-API routing for the Alpaca APIs
 * (Trading, Market Data, Broker, AuthX) - all generated by Orval from the
 * official specs (run `bun run generate`). Every client routes HTTP through the
 * shared {@link makeMutator | mutator}, which resolves host (paper/live +
 * `ALPACA_*_URL` overrides; live by default) and auth per API.
 *
 * @see https://docs.alpaca.markets/
 */

// Per-API host + auth routing, and the shared mutator behind every generated client.
export { API_ROUTING } from './api-routing';
export type { ApiMeta, AuthStrategy } from './api-routing';
export { makeMutator, tradingMutator, dataMutator, brokerMutator, authxMutator } from './mutator';

// Typed fetch clients, one namespace per API - e.g. `tradingApi.getAccount()`,
// `dataApi.stockLatestQuoteSingle(...)`. Credentials/host come from the env the
// mutator reads (ALPACA_API_KEY/SECRET, ALPACA_ENV).
export * as tradingApi from './generated/trading/client';
export * as dataApi from './generated/data/client';
export * as brokerApi from './generated/broker/client';
export * as authxApi from './generated/authx/client';

// Model (schema) types, one namespace per API - e.g. `tradingModel.Account`.
export * as tradingModel from './generated/trading/model';
export * as dataModel from './generated/data/model';
export * as brokerModel from './generated/broker/model';
export * as authxModel from './generated/authx/model';

// Hand-written WebSocket streaming clients - streaming isn't in the OpenAPI specs,
// so (like the mutator) there's nothing to generate. See the README's Streaming
// section for usage. `StreamClient` is the shared connect/auth/reconnect engine;
// `TradingStreamClient` and the `*DataStream` factories are the typed, ready-to-use
// clients built on it. Each is a plain `AsyncIterable` - no `EventEmitter` - so
// there's no event to forget to listen for; `for await` is the only consumer API.
export { AsyncQueue, StreamClient } from './streaming/client';
export type { ReconnectOptions, StreamClientOptions, StreamClientState, StreamEvent } from './streaming/client';
export { TradingStreamClient } from './streaming/trading-client';
export type { TradeUpdate, TradeUpdateEvent, TradingStreamEvent, TradingStreamOptions } from './streaming/trading-client';
export { cryptoDataStream, MarketDataStreamClient, newsDataStream, optionDataStream, stockDataStream } from './streaming/market-data-client';
export type {
  CryptoMessage,
  MarketDataStreamEvent,
  MarketDataStreamOptions,
  NewsMessage,
  OptionMessage,
  StockMessage,
  SubscriptionAck,
} from './streaming/market-data-client';
export type { OptionFeed, StockFeed } from './streaming/routes';
// `optionDataStream()` already wires these up by default (the option feed requires real
// MessagePack both ways - see market-data-client.ts's module doc). Exported so
// `TradingStreamOptions`/`MarketDataStreamOptions`' `encode`/`decode` can opt into the same
// codec elsewhere, e.g. if a transport negotiates `Content-Type: application/msgpack`.
export { decode as decodeMsgPack, encode as encodeMsgPack } from './streaming/msgpack';
