/**
 * @alpaca-open-api/core
 *
 * Generated OpenAPI types, per-API routing, and typed **fetch clients** for the
 * Alpaca APIs (Trading, Market Data, Broker, AuthX). Types are generated by
 * `openapi-typescript` and the clients by Orval — run `bun run generate`. Every
 * client routes HTTP through the shared {@link makeMutator | mutator}, which
 * resolves host (paper/live + `ALPACA_*_URL` overrides) and auth per API.
 *
 * @see https://docs.alpaca.markets/
 */

// Generated OpenAPI types (openapi-typescript).
export type {
  paths as TradingPaths,
  components as TradingComponents,
  operations as TradingOperations,
} from './types/trading-api';
export type { paths as MarketDataPaths, components as MarketDataComponents } from './types/market-data-api';
export type { paths as BrokerPaths, components as BrokerComponents } from './types/broker-api';
export type { paths as AuthXPaths, components as AuthXComponents } from './types/authx';
// Trading API types as the default for backward compatibility.
export type { paths, components } from './types/trading-api';

// Per-API host + auth routing, and the shared mutator behind every generated client.
export { API_ROUTING } from './api-routing';
export type { ApiMeta, AuthStrategy } from './api-routing';
export { makeMutator, tradingMutator, dataMutator, brokerMutator, authxMutator } from './mutator';

// Typed fetch clients, one namespace per API — e.g. `tradingApi.getAccount()`,
// `dataApi.stockLatestQuoteSingle(...)`. Credentials/host come from the env the
// mutator reads (ALPACA_API_KEY/SECRET, ALPACA_ENV).
export * as tradingApi from './generated/trading/client';
export * as dataApi from './generated/data/client';
export * as brokerApi from './generated/broker/client';
export * as authxApi from './generated/authx/client';
