/**
 * Alpaca API TypeScript Types
 * 
 * This file contains TypeScript types generated from the Alpaca OpenAPI specification.
 * 
 * To generate/update these types, run:
 *   bun run generate
 * 
 * This will fetch the latest OpenAPI spec from https://docs.alpaca.markets/openapi
 * and generate TypeScript types using openapi-typescript.
 * 
 * @see https://docs.alpaca.markets/openapi
 * @see https://github.com/drwpow/openapi-typescript
 */

// This file will be generated by running: bun run generate
// The types below are placeholders that match the structure of generated openapi-typescript types

export interface paths {
  '/v2/account': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Account'];
          };
        };
      };
    };
  };
  '/v2/positions': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Position'][];
          };
        };
      };
    };
  };
  '/v2/orders': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Order'][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['OrderRequest'];
        };
      };
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
      };
    };
  };
  '/v2/orders/{order_id}': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
      };
    };
    delete: {
      responses: {
        204: {
          content: never;
        };
      };
    };
  };
  '/v2/clock': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Clock'];
          };
        };
      };
    };
  };
  '/v2/stocks/{symbol}/trades/latest': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['LatestTrade'];
          };
        };
      };
    };
  };
  '/v2/stocks/{symbol}/quotes/latest': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['LatestQuote'];
          };
        };
      };
    };
  };
  '/v2/stocks/{symbol}/bars': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Bars'];
          };
        };
      };
    };
  };
  '/v2/stocks/snapshots': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': Record<string, components['schemas']['Snapshot']>;
          };
        };
      };
    };
  };
  '/v2/assets/{symbol}': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Asset'];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Account: {
      id: string;
      account_number: string;
      status: string;
      crypto_status?: string;
      currency: string;
      buying_power: string;
      regt_buying_power: string;
      daytrading_buying_power: string;
      non_marginable_buying_power: string;
      cash: string;
      accrued_fees: string;
      pending_transfer_out?: string;
      pending_transfer_in?: string;
      portfolio_value: string;
      pattern_day_trader: boolean;
      trading_blocked: boolean;
      transfers_blocked: boolean;
      account_blocked: boolean;
      created_at: string;
      trade_suspended_by_user: boolean;
      multiplier: string;
      shorting_enabled: boolean;
      equity: string;
      last_equity: string;
      long_market_value: string;
      short_market_value: string;
      initial_margin: string;
      maintenance_margin: string;
      last_maintenance_margin: string;
      sma: string;
      daytrade_count: number;
    };
    Position: {
      asset_id: string;
      symbol: string;
      exchange: string;
      asset_class: string;
      asset_marginable: boolean;
      qty: string;
      avg_entry_price: string;
      side: string;
      market_value: string;
      cost_basis: string;
      unrealized_pl: string;
      unrealized_plpc: string;
      unrealized_intraday_pl: string;
      unrealized_intraday_plpc: string;
      current_price: string;
      lastday_price: string;
      change_today: string;
      swap_rate?: string;
      avg_entry_swap_rate?: string;
      usd?: {
        avg_entry_price: string;
        market_value: string;
        cost_basis: string;
        unrealized_pl: string;
        unrealized_plpc: string;
        unrealized_intraday_pl: string;
        unrealized_intraday_plpc: string;
        current_price: string;
        lastday_price: string;
        change_today: string;
      };
      qty_available: string;
    };
    Order: {
      id: string;
      client_order_id: string;
      created_at: string;
      updated_at: string;
      submitted_at: string;
      filled_at?: string;
      expired_at?: string;
      canceled_at?: string;
      failed_at?: string;
      replaced_at?: string;
      replaced_by?: string;
      replaces?: string;
      asset_id: string;
      symbol: string;
      asset_class: string;
      notional?: string;
      qty?: string;
      filled_qty: string;
      filled_avg_price?: string;
      order_class: string;
      order_type?: string;
      type: string;
      side: string;
      time_in_force: string;
      limit_price?: string;
      stop_price?: string;
      status: string;
      extended_hours: boolean;
      legs?: components['schemas']['Order'][];
      trail_percent?: string;
      trail_price?: string;
      hwm?: string;
      subtag?: string;
      source?: string;
    };
    OrderRequest: {
      symbol: string;
      qty?: string;
      notional?: string;
      side: 'buy' | 'sell';
      type: 'market' | 'limit' | 'stop' | 'stop_limit' | 'trailing_stop';
      time_in_force: 'day' | 'gtc' | 'opg' | 'cls' | 'ioc' | 'fok';
      limit_price?: string;
      stop_price?: string;
      trail_price?: string;
      trail_percent?: string;
      extended_hours?: boolean;
      client_order_id?: string;
      order_class?: 'simple' | 'bracket' | 'oco' | 'oto';
      take_profit?: {
        limit_price: string;
      };
      stop_loss?: {
        stop_price: string;
        limit_price?: string;
      };
    };
    Clock: {
      timestamp: string;
      is_open: boolean;
      next_open: string;
      next_close: string;
    };
    Trade: {
      t: string;
      x: string;
      p: number;
      s: number;
      c: string[];
      i: number;
      z: string;
    };
    LatestTrade: {
      symbol: string;
      trade: components['schemas']['Trade'];
    };
    Quote: {
      t: string;
      ax: string;
      ap: number;
      as: number;
      bx: string;
      bp: number;
      bs: number;
      c: string[];
      z: string;
    };
    LatestQuote: {
      symbol: string;
      quote: components['schemas']['Quote'];
    };
    Bar: {
      t: string;
      o: number;
      h: number;
      l: number;
      c: number;
      v: number;
      n: number;
      vw: number;
    };
    Bars: {
      bars: components['schemas']['Bar'][];
      symbol: string;
      next_page_token?: string;
    };
    Snapshot: {
      latestTrade?: components['schemas']['Trade'];
      latestQuote?: components['schemas']['Quote'];
      minuteBar?: components['schemas']['Bar'];
      dailyBar?: components['schemas']['Bar'];
      prevDailyBar?: components['schemas']['Bar'];
    };
    Asset: {
      id: string;
      class: string;
      exchange: string;
      symbol: string;
      name: string;
      status: string;
      tradable: boolean;
      marginable: boolean;
      maintenance_margin_requirement: number;
      shortable: boolean;
      easy_to_borrow: boolean;
      fractionable: boolean;
      min_order_size?: string;
      min_trade_increment?: string;
      price_increment?: string;
      attributes: string[];
    };
  };
}

