/**
 * Post-processing for the Orval-generated MCP output (run right after `orval`).
 *
 * Fix-ups for `@orval/mcp` quirks when used with `override.mutator`:
 *  1. The `<api>Mutator` import is emitted into `handlers.ts` (unused) instead of
 *     `http-client.ts` (where it is called) - we add it to http-client so the
 *     bundle resolves at runtime.
 *  2. `server.ts` (its own stdio entry) is unused - `compose.ts` composes all four
 *     APIs onto one server - and references response schemas we disable, so it
 *     does not type-check. We delete it.
 *  3. We emit a `register.ts` per API: a statically-typed `register<Api>Tools`
 *     function with one `server.registerTool` call per operation (handler + Zod
 *     input schemas referenced by name), so `compose.ts` registers tools without
 *     reflecting over module exports or casting.
 *
 * The earlier query+body arg-order quirk (and optional bodies typed as required)
 * was fixed upstream in `@orval/mcp` (orval PR #3600), released in orval 8.18.0,
 * so no post-gen swap is needed.
 */

import {
  existsSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const generatedDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'generated',
);

const pascal = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * Emit `register.ts` for one API by reading the generated `handlers.ts` and
 * `tool-schemas.zod.ts`: one `server.registerTool` call per `<op>Handler`, paired
 * with its Zod input (`<Op>Params`/`<Op>QueryParams`/`<Op>Body`). Operations whose
 * handler takes args but have no generated Zod (form-encoded bodies) get a
 * permissive `z.record` body and are cast to the handler's own arg type.
 */
const generateRegister = (api: string, apiDir: string): void => {
  const handlersSrc = readFileSync(join(apiDir, 'handlers.ts'), 'utf8');
  const zodSrc = readFileSync(join(apiDir, 'tool-schemas.zod.ts'), 'utf8');
  const zodExports = new Set(
    [...zodSrc.matchAll(/export const (\w+) =/g)].map((m) => m[1]),
  );

  let usesZod = false;
  let usesSchemas = false;
  const calls: string[] = [];

  for (const match of handlersSrc.matchAll(
    /export const (\w+)Handler = async \(\s*(\w+)/g,
  )) {
    const op = match[1];
    const head = `ctx.tool('${op}'), { description: ctx.describe('${op}')`;

    if (match[2] !== 'args') {
      calls.push(
        `  server.registerTool(${head} }, async () => ctx.strip('${op}', await handlers.${op}Handler()));`,
      );
      continue;
    }

    const P = pascal(op);
    const parts: string[] = [];
    if (zodExports.has(`${P}Params`)) parts.push(`pathParams: schemas.${P}Params`);
    if (zodExports.has(`${P}QueryParams`))
      parts.push(`queryParams: schemas.${P}QueryParams`);
    if (zodExports.has(`${P}Body`)) parts.push(`bodyParams: schemas.${P}Body`);

    if (parts.length > 0) {
      usesSchemas = true;
      calls.push(
        `  server.registerTool(${head}, inputSchema: { ${parts.join(', ')} } }, async (args) => ctx.strip('${op}', await handlers.${op}Handler(args)));`,
      );
    } else {
      // Form-encoded body with no generated Zod: validate permissively, then cast
      // the validated args to the handler's own parameter type.
      usesZod = true;
      calls.push(
        `  server.registerTool(${head}, inputSchema: { bodyParams: z.record(z.string(), z.string()) } }, async (args) => ctx.strip('${op}', await handlers.${op}Handler(args as unknown as Parameters<typeof handlers.${op}Handler>[0])));`,
      );
    }
  }

  const imports = [
    usesZod ? `import { z } from 'zod';` : '',
    `import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';`,
    `import type { RegisterContext } from '../../registry';`,
    `import * as handlers from './handlers';`,
    usesSchemas ? `import * as schemas from './tool-schemas.zod';` : '',
  ]
    .filter(Boolean)
    .join('\n');

  const content = `// Generated by scripts/postgen.ts - do not edit.
${imports}

export const register${pascal(api)}Tools = (
  server: McpServer,
  ctx: RegisterContext,
): void => {
${calls.join('\n')}
};
`;

  writeFileSync(join(apiDir, 'register.ts'), content);
};

for (const api of readdirSync(generatedDir)) {
  const apiDir = join(generatedDir, api);

  const server = join(apiDir, 'server.ts');
  if (existsSync(server)) rmSync(server);

  const httpClient = join(apiDir, 'http-client.ts');
  if (existsSync(httpClient)) {
    const importLine = `import { ${api}Mutator } from '../../mutator';`;
    const source = readFileSync(httpClient, 'utf8');
    if (!source.includes(importLine))
      writeFileSync(httpClient, `${importLine}\n${source}`);
  }

  generateRegister(api, apiDir);
}

process.stderr.write(
  'postgen: injected mutator imports, removed unused server.ts, generated register.ts\n',
);
