#!/usr/bin/env node
/**
 * Alpaca MCP server - CLI entry point.
 *
 * Exposes the entire Alpaca API surface (Trading, Market Data, Broker, AuthX) to
 * MCP clients. The per-operation tool surface is generated by Orval (`client:
 * 'mcp'`, see `orval.config.ts`) and composed onto one server by `./compose.ts`;
 * every HTTP call is routed through the API's mutator (`./mutator.ts`), which
 * supplies the host + auth. This file only handles the CLI: flags, env, and which
 * transport to connect.
 *
 * Two transports:
 *   - `stdio` (default) - single-tenant; credentials come from the process env.
 *   - `streamable-http` (opt-in via `--transport http` / `ALPACA_TRANSPORT=http`) -
 *     multi-tenant; the server holds no secrets and each request carries its own
 *     Alpaca credentials in headers (see `./http.ts`).
 *
 * Published as the `@alpaca-open-api/mcp` CLI - `npx @alpaca-open-api/mcp`
 * (or `bun run src/mcp.ts`). Configure via environment variables:
 *
 *   ALPACA_API_KEY, ALPACA_API_SECRET   (required for stdio; live and paper keys differ)
 *   ALPACA_ENV = paper | live            (default: live)
 *   ALPACA_TOOLSETS = trading,data,...    (optional: restrict registered toolsets; default: trading,data)
 *   ALPACA_{TRADING,DATA,BROKER,AUTHX}_URL  (optional per-API base-URL overrides)
 *   ALPACA_TRANSPORT = stdio | http       (default: stdio; or --transport)
 *   ALPACA_HTTP_PORT / ALPACA_HTTP_HOST / ALPACA_HTTP_PATH   (http transport; default 3000 / 127.0.0.1 / /mcp)
 */

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { buildServer } from './compose';
import { startHttpServer } from './http';
import { version } from '../package.json';

const argv = process.argv.slice(2);

/** Reads a `--flag value` or `--flag=value` option from argv. */
function flagValue(name: string): string | undefined {
  const i = argv.indexOf(name);
  if (i !== -1 && i + 1 < argv.length) return argv[i + 1];
  const eq = argv.find((a) => a.startsWith(`${name}=`));
  return eq?.slice(name.length + 1);
}

if (argv.includes('--help') || argv.includes('-h')) {
  process.stdout.write(
    `alpaca-mcp - MCP server for the Alpaca Markets API\n\n` +
      `Registers every Alpaca endpoint as an \`alpaca_<operationId>\` tool.\n\n` +
      `Usage:\n` +
      `  npx @alpaca-open-api/mcp                     Start on stdio (default; for local MCP clients)\n` +
      `  npx @alpaca-open-api/mcp --transport http    Start the streamable-http server (remote, multi-tenant)\n\n` +
      `In http mode the server holds no credentials: each request passes its own Alpaca\n` +
      `keys in the APCA-API-KEY-ID / APCA-API-SECRET-KEY headers (X-Alpaca-Env: paper|live),\n` +
      `and credential-less requests are rejected. Bind it behind a TLS proxy to expose it.\n\n` +
      `Environment:\n` +
      `  ALPACA_API_KEY          (stdio)     API key (live and paper keys differ)\n` +
      `  ALPACA_API_SECRET       (stdio)     API secret\n` +
      `  ALPACA_ENV              paper|live  (default: live)\n` +
      `  ALPACA_TOOLSETS         csv         restrict to a subset: trading,data,broker,authx (default: trading,data)\n` +
      `  ALPACA_{TRADING,DATA,BROKER,AUTHX}_URL   per-API base-URL overrides\n` +
      `  ALPACA_TRANSPORT        stdio|http  (default: stdio; or --transport)\n` +
      `  ALPACA_HTTP_PORT        number      (default: 3000; http transport)\n` +
      `  ALPACA_HTTP_HOST        host        (default: 127.0.0.1; http transport)\n` +
      `  ALPACA_HTTP_PATH        path        (default: /mcp; http transport)\n`
  );
  process.exit(0);
}
if (argv.includes('--version') || argv.includes('-v')) {
  process.stdout.write(`${version}\n`);
  process.exit(0);
}

const toolsetsEnv = process.env.ALPACA_TOOLSETS?.trim();
const enabledToolsets = toolsetsEnv
  ? toolsetsEnv
      .split(',')
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean)
  : undefined;

const transport = (flagValue('--transport') ?? process.env.ALPACA_TRANSPORT ?? 'stdio').toLowerCase();
const toolsetsNote = enabledToolsets?.length ? ` (toolsets: ${enabledToolsets.join(', ')})` : '';

if (transport === 'http' || transport === 'streamable-http') {
  const port = Number(process.env.ALPACA_HTTP_PORT ?? 3000);
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    process.stderr.write(`Invalid ALPACA_HTTP_PORT: ${process.env.ALPACA_HTTP_PORT}\n`);
    process.exit(1);
  }
  const host = process.env.ALPACA_HTTP_HOST ?? '127.0.0.1';
  const path = process.env.ALPACA_HTTP_PATH ?? '/mcp';
  // One-time build to report the tool count (the http transport rebuilds per request).
  const { count } = buildServer(enabledToolsets);
  await startHttpServer({ port, host, path, toolsets: enabledToolsets });
  process.stderr.write(
    `alpaca-api MCP server (streamable-http) ready - ${count} tools, listening on http://${host}:${port}${path}. ` +
      `Credentials are read per request from the APCA-API-KEY-ID / APCA-API-SECRET-KEY headers ` +
      `(X-Alpaca-Env: paper|live)${toolsetsNote}.\n`
  );
} else if (transport === 'stdio') {
  if (!process.env.ALPACA_API_KEY || !process.env.ALPACA_API_SECRET) {
    process.stderr.write(
      'Warning: ALPACA_API_KEY / ALPACA_API_SECRET are not set; calls will fail auth. ' +
        'Defaulting to live - set ALPACA_ENV=paper for paper (keys differ between live and paper).\n'
    );
  }
  const { server, count } = buildServer(enabledToolsets);
  await server.connect(new StdioServerTransport());
  process.stderr.write(`alpaca-api MCP server ready - ${count} tools registered${toolsetsNote}.\n`);
} else {
  process.stderr.write(`Unknown transport: ${transport} (expected 'stdio' or 'http').\n`);
  process.exit(1);
}
