#!/usr/bin/env node
/**
 * Alpaca MCP server - CLI entry point.
 *
 * Exposes the entire Alpaca API surface (Trading, Market Data, Broker, AuthX) to
 * MCP clients. The per-operation tool surface is generated by Orval (`client:
 * 'mcp'`, see `orval.config.ts`) and composed onto one server by `./compose.ts`;
 * every HTTP call is routed through the API's mutator (`./mutator.ts`), which
 * supplies the host + auth. This file only handles the CLI: flags, env, and the
 * stdio transport.
 *
 * Published as the `@alpaca-open-api/mcp` CLI - `npx @alpaca-open-api/mcp`
 * (or `bun run src/mcp.ts`). Configure via environment variables:
 *
 *   ALPACA_API_KEY, ALPACA_API_SECRET   (required; live and paper keys differ)
 *   ALPACA_ENV = paper | live            (default: live)
 *   ALPACA_MCP_APIS = trading,data,...     (optional: restrict the registered APIs)
 *   ALPACA_{TRADING,DATA,BROKER,AUTHX}_URL  (optional per-API base-URL overrides)
 */

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { buildServer } from './compose';

const argv = process.argv.slice(2);
if (argv.includes('--help') || argv.includes('-h')) {
  process.stdout.write(
    `alpaca-mcp - MCP server for the Alpaca Markets API\n\n` +
      `Registers every Alpaca endpoint as an \`alpaca_<operationId>\` tool.\n\n` +
      `Usage:\n` +
      `  npx @alpaca-open-api/mcp        Start the server on stdio (for MCP clients)\n\n` +
      `Environment:\n` +
      `  ALPACA_API_KEY          (required)  API key (live and paper keys differ)\n` +
      `  ALPACA_API_SECRET       (required)  API secret\n` +
      `  ALPACA_ENV              paper|live  (default: live)\n` +
      `  ALPACA_MCP_APIS         csv         restrict to a subset: trading,data,broker,authx\n` +
      `  ALPACA_{TRADING,DATA,BROKER,AUTHX}_URL   per-API base-URL overrides\n`
  );
  process.exit(0);
}
if (argv.includes('--version') || argv.includes('-v')) {
  process.stdout.write('0.1.0\n');
  process.exit(0);
}

if (!process.env.ALPACA_API_KEY || !process.env.ALPACA_API_SECRET) {
  process.stderr.write(
    'Warning: ALPACA_API_KEY / ALPACA_API_SECRET are not set; calls will fail auth. ' +
      'Defaulting to live - set ALPACA_ENV=paper for paper (keys differ between live and paper).\n'
  );
}

const enabledApis = (process.env.ALPACA_MCP_APIS ?? '')
  .split(',')
  .map((s) => s.trim().toLowerCase())
  .filter(Boolean);

const { server, count } = buildServer(enabledApis);
await server.connect(new StdioServerTransport());
process.stderr.write(
  `alpaca-api MCP server ready - ${count} tools registered` +
    `${enabledApis.length ? ` (apis: ${enabledApis.join(', ')})` : ''}.\n`
);
